# -*- coding: utf-8 -*-
from odoo import _, api, fields, models
from odoo.exceptions import UserError
from .aifa_grade_price import GRADES


class AifaFieldPurchase(models.Model):
    """Field Purchase Order captured at a rural collection centre (FRS-1.2).

    The record is designed to be created either in the web client or by the
    offline mobile client replaying its local queue through
    ``/aifa/api/v1/sourcing/field-purchase``.  ``client_ref`` carries the
    device-side UUID and is what makes the replay idempotent.
    """

    _name = "aifa.field.purchase"
    _description = "Field Purchase Order"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _order = "date desc, name desc"

    name = fields.Char(required=True, copy=False, readonly=True, default="New", index=True)
    date = fields.Date(required=True, default=fields.Date.context_today, tracking=True)
    centre_id = fields.Many2one("aifa.collection.centre", required=True, tracking=True)
    region_id = fields.Many2one(related="centre_id.region_id", store=True, readonly=True)
    agent_id = fields.Many2one(
        "res.users", string="Field Agent", required=True,
        default=lambda self: self.env.user, tracking=True,
    )
    line_ids = fields.One2many("aifa.field.purchase.line", "purchase_id", string="Lines")
    state = fields.Selection(
        [("draft", "Draft"), ("confirmed", "Confirmed"),
         ("dispatched", "Dispatched"), ("done", "Received"), ("cancel", "Cancelled")],
        default="draft", tracking=True, copy=False,
    )
    total_weight_kg = fields.Float(compute="_compute_totals", store=True, digits=(12, 3))
    amount_total = fields.Monetary(compute="_compute_totals", store=True,
                                   currency_field="currency_id")
    currency_id = fields.Many2one(
        "res.currency", default=lambda self: self.env.company.currency_id, readonly=True,
    )
    intake_ids = fields.One2many("aifa.intake.batch", "field_purchase_id", string="Intake Batches")
    intake_count = fields.Integer(compute="_compute_intake_count")

    # --- transport manifest (FRS-1.7) ---
    truck_plate = fields.Char(string="Truck Plate")
    driver_name = fields.Char()
    driver_phone = fields.Char()
    dispatch_datetime = fields.Datetime()
    transit_tare_kg = fields.Float(string="Transit Tare (kg)", digits=(12, 3))

    # --- offline sync metadata (FRS-1.2) ---
    client_ref = fields.Char(
        string="Device Reference", copy=False, index=True, readonly=True,
        help="UUID generated by the offline mobile client; guarantees idempotent replay.",
    )
    device_id = fields.Char(readonly=True)
    captured_offline = fields.Boolean(readonly=True)
    synced_at = fields.Datetime(readonly=True)
    gps_lat = fields.Float(digits=(10, 6), readonly=True)
    gps_lng = fields.Float(digits=(10, 6), readonly=True)

    _sql_constraints = [
        ("client_ref_uniq", "unique(client_ref)",
         "This field purchase has already been synchronised from the mobile device."),
    ]

    @api.depends("line_ids.net_weight_kg", "line_ids.subtotal")
    def _compute_totals(self):
        for order in self:
            order.total_weight_kg = sum(order.line_ids.mapped("net_weight_kg"))
            order.amount_total = sum(order.line_ids.mapped("subtotal"))

    @api.depends("intake_ids")
    def _compute_intake_count(self):
        for order in self:
            order.intake_count = len(order.intake_ids)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("name", "New") == "New":
                vals["name"] = self.env["ir.sequence"].next_by_code("aifa.field.purchase") or "New"
        return super().create(vals_list)

    def action_confirm(self):
        """Confirm the purchase and materialise one intake batch per line."""
        for order in self:
            if order.state != "draft":
                raise UserError(_("Only a draft field purchase can be confirmed."))
            if not order.line_ids:
                raise UserError(_("Add at least one weighing line before confirming."))
            batches = self.env["aifa.intake.batch"]
            for line in order.line_ids:
                batches |= line._create_intake_batch()
            order.state = "confirmed"
            order.message_post(
                body=_("Confirmed: %s kg across %s intake batch(es).")
                % (round(order.total_weight_kg, 2), len(batches))
            )
        return True

    def action_dispatch(self):
        for order in self:
            if order.state != "confirmed":
                raise UserError(_("Confirm the field purchase before dispatching the truck."))
            if not order.truck_plate:
                raise UserError(_("Record the truck plate before generating the dispatch manifest."))
            order.write({
                "state": "dispatched",
                "dispatch_datetime": order.dispatch_datetime or fields.Datetime.now(),
            })
            order.intake_ids.filtered(lambda b: b.state == "weighed").write({"state": "in_transit"})
        return True

    def action_cancel(self):
        for order in self:
            if order.intake_ids.filtered(lambda b: b.state in ("received", "accepted", "done")):
                raise UserError(
                    _("Fruit from %s has already been received at the plant; cancel the "
                      "individual intake batches instead.") % order.name
                )
            order.intake_ids.write({"state": "cancel"})
            order.state = "cancel"
        return True

    def action_draft(self):
        self.filtered(lambda o: o.state == "cancel").write({"state": "draft"})

    def action_view_intakes(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Intake Batches"),
            "res_model": "aifa.intake.batch",
            "view_mode": "tree,form",
            "domain": [("field_purchase_id", "=", self.id)],
        }


class AifaFieldPurchaseLine(models.Model):
    _name = "aifa.field.purchase.line"
    _description = "Field Purchase Line"
    _order = "purchase_id, sequence, id"

    purchase_id = fields.Many2one("aifa.field.purchase", required=True, ondelete="cascade")
    sequence = fields.Integer(default=10)
    farmer_id = fields.Many2one("aifa.farmer", required=True)
    crop_id = fields.Many2one("aifa.crop", required=True)
    variety_id = fields.Many2one("aifa.crop.variety", domain="[('crop_id', '=', crop_id)]")
    plot_id = fields.Many2one("aifa.farmer.plot", domain="[('farmer_id', '=', farmer_id)]")
    grade = fields.Selection(GRADES, required=True, default="a")

    gross_weight_kg = fields.Float(required=True, digits=(12, 3))
    crate_count = fields.Integer(string="Crates")
    crate_tare_kg = fields.Float(
        string="Crate Tare (kg)", default=1.8, digits=(8, 3),
        help="Empty weight of one reusable plastic crate.",
    )
    net_weight_kg = fields.Float(compute="_compute_net", store=True, digits=(12, 3))
    price_per_kg = fields.Monetary(currency_field="currency_id")
    subtotal = fields.Monetary(compute="_compute_net", store=True, currency_field="currency_id")
    currency_id = fields.Many2one(related="purchase_id.currency_id", readonly=True)

    brix = fields.Float(string="Brix", digits=(5, 2))
    scale_serial = fields.Char(
        string="Scale ID",
        help="Serial of the Bluetooth platform scale that transmitted the weight (FRS-1.3).",
    )
    scale_verified = fields.Boolean(
        string="Machine Weighed", readonly=True,
        help="True when the weight arrived straight from the scale rather than being typed.",
    )
    note = fields.Char()

    @api.depends("gross_weight_kg", "crate_count", "crate_tare_kg", "price_per_kg")
    def _compute_net(self):
        for line in self:
            tare = line.crate_count * line.crate_tare_kg
            line.net_weight_kg = max(line.gross_weight_kg - tare, 0.0)
            line.subtotal = line.net_weight_kg * line.price_per_kg

    @api.onchange("crop_id", "grade", "purchase_id")
    def _onchange_price(self):
        if self.crop_id and self.grade:
            region = self.purchase_id.region_id or self.farmer_id.region_id
            price = self.env["aifa.grade.price"].resolve(
                self.crop_id, self.grade, region=region, date=self.purchase_id.date
            )
            if price:
                self.price_per_kg = price.price_per_kg

    @api.onchange("farmer_id")
    def _onchange_farmer(self):
        if self.farmer_id and not self.crop_id and len(self.farmer_id.crop_ids) == 1:
            self.crop_id = self.farmer_id.crop_ids

    def _create_intake_batch(self):
        self.ensure_one()
        return self.env["aifa.intake.batch"].create({
            "field_purchase_id": self.purchase_id.id,
            "farmer_id": self.farmer_id.id,
            "plot_id": self.plot_id.id,
            "crop_id": self.crop_id.id,
            "variety_id": self.variety_id.id,
            "centre_id": self.purchase_id.centre_id.id,
            "intake_date": self.purchase_id.date,
            "field_grade": self.grade,
            "gross_weight_kg": self.gross_weight_kg,
            "crate_count": self.crate_count,
            "crate_tare_kg": self.crate_tare_kg,
            "price_per_kg": self.price_per_kg,
            "brix": self.brix,
            "scale_serial": self.scale_serial,
            "state": "weighed",
        })
